/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const derive_secret: (a: number, b: number, c: number, d: bigint) => [number, number, number, number];
export const format_amount: (a: bigint) => [number, number];
export const format_public_webcash: (a: number, b: number, c: bigint) => [number, number];
export const format_webcash: (a: number, b: number, c: bigint) => [number, number];
export const generate_master_secret: () => [number, number, number, number];
export const parse_amount: (a: number, b: number) => [bigint, number, number];
export const parse_webcash: (a: number, b: number) => [number, number, number];
export const sdk_version: () => [number, number];
export const secret_to_public: (a: number, b: number) => [number, number];
export const sha256_hex: (a: number, b: number) => [number, number];
export const verify_webcash: (a: number, b: number, c: number, d: number) => any;
export const wallet_balance: (a: number, b: number, c: number, d: number) => [bigint, number, number];
export const wallet_check: (a: number, b: number, c: number, d: number) => any;
export const wallet_create: (a: number, b: number) => [number, number, number, number];
export const wallet_create_with_secret: (a: number, b: number, c: number, d: number) => any;
export const wallet_decrypt_with_password: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wallet_encrypt_with_password: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wallet_export_snapshot: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wallet_import_snapshot: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wallet_insert: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const wallet_list_webcash: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wallet_master_secret: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wallet_merge: (a: number, b: number, c: number, d: number, e: number) => any;
export const wallet_pay: (a: number, b: number, c: number, d: number, e: bigint) => any;
export const wallet_recover: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wallet_recover_from_wallet: (a: number, b: number, c: number, d: number, e: number) => any;
export const wallet_stats: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const init_panic_hook: () => void;
export const wasm_bindgen__convert__closures_____invoke__h37de7bed023b949e: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1908459014efb51c: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0c37c10f85431039: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
